UPDATE attendees SET
                     participants_after = 0,
                     tire_40_after = 0,
                     tire_80_after = 0,
                     tire_120_after = 0,
                     tire_200_after = 0,
                     tire_300_after = 0,
                     tire_600_after = 0,
                     participants_after = 0;